### ISSUE TITLE
Upgrade 2.0.0 -> 3.0.1 failed

### ISSUE THREAD

**Issue by MutterOberin** [opentk/opentk#825]
I upgraded my project from using OpenTK 2.0.0 to 3.0.1. Using NuGet Packages and .Net 4.6.

Along the way I had to change "BlendingFactorSrc" and "BlendingFactorDst" to "BlendingFactor since the signature of BlendFunc changed. 

After upgrading I have a black screen instead of OpenGL rendering of the scene.

Am I missing important changes happened? Is there a changelog?

**Comment by varon** [comment]
It should be compatible generally speaking. The problem description is kinda vague; can you paste a minimal example of code that works in one version but not the other?


@Nihlus ?

**Comment by Nihlus** [comment]
No clue. Many other projects work fine.

**Comment by MutterOberin** [comment]
Its a quite big project, so of course it can be unrelated but it is definitely reproducible. 
There are two modes: deferred shading which gives complete black in 3.0.1 and forward shading where all objects are black in 3.0.1. Could someone take a closer look into the blending? Can it be caused by that?

**Comment by varon** [comment]
It's really hard to call here. I've got no problems with blending on my side.

Double check the GL specifications/docs; any changes should be closer to it than before.

Finally, you can always try to cast the old values and see what happens.

**Comment by MutterOberin** [comment]
I will investigate that further and let you know.

**Comment by MutterOberin** [comment]
I figured that 3.0.0-pre is also working but 3.0.0 and 3.0.1 not. It seems also not related to the blending. I deactivated everything except a camera and VAO build / call and still get black objects. Will try to provide a minimal example with the same behavior.

**Comment by Masclaux** [comment]
Hello 

did all you shader compile ? 

After upgrade from 3.0.0-pre to 3.0.1 I have issue with my fragment shader :  

`[ ERROR ] : Shader Compilation fail for ../data/Shaders/Default.vcg : (0) : error C0000: syntax error, unexpected $end at token "<EOF>"
 at ShaderBase.cs line 64`

I have to add an "end of line" at the end of my file.

this not work on 3.0.1
![image](https://user-images.githubusercontent.com/11290292/47854032-f1909f80-dde0-11e8-9b13-cfb8687bee3d.png)

need to do that 

![image](https://user-images.githubusercontent.com/11290292/47854062-09682380-dde1-11e8-8518-fda6bfd18462.png)

**Comment by DylanFPS** [comment]
Yes. The compiler expects CRLF (\r\n) to be the last characters of the file.

**Comment by Masclaux** [comment]
For me yes it fix it. Thank you. 

Sorry to have parasite @MutterOberin thread I was thinking we have a similar issue.

**Comment by MutterOberin** [comment]
No worries @Masclaux ! But my shaders are all fine or at least I can not see any errors (GL Debug Proc) Still have to find the cause of my black screen, though.
